<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>Serilog.Sinks.GrafanaLoki</AssemblyName>
    <title>Serilog.Sinks.GrafanaLoki</title>
    <Description>A Serilog Sink for Grafana's Loki log aggregator</Description>
    <Authors>George Benjamin-Schonberger</Authors>
    <Company>George Benjamin-Schonberger</Company>
    <Copyright>George Benjamin-Schonberger 2026</Copyright>
    <AssemblyVersion>1.2.0.12</AssemblyVersion>
    <FileVersion>1.2.0.12</FileVersion>
    <Version>1.2.0</Version>
    <PackageId>Serilog.Sinks.GrafanaLoki</PackageId>
    <PackageTags>loki,grafana,serilog,sinks</PackageTags>
    <PackageProjectUrl>https://adeotek.github.io/Serilog.Sinks.GrafanaLoki/</PackageProjectUrl>
    <PackageLicense>https://github.com/adeotek/Serilog.Sinks.GrafanaLoki/blob/main/LICENSE</PackageLicense>
    <RepositoryUrl>https://github.com/adeotek/Serilog.Sinks.GrafanaLoki/</RepositoryUrl>
    <RepositoryType>Git</RepositoryType>
    <PackageIcon>PackageIcon.png</PackageIcon>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageVersion>1.2.0</PackageVersion>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Serilog.Sinks.GrafanaLoki.Tests" />
  </ItemGroup>

  <ItemGroup>

    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.10" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.301" PrivateAssets="all">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Include="../LICENSE">
      <Pack>True</Pack>
      <PackagePath>/</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="../assets/PackageIcon.png">
      <Pack>True</Pack>
      <PackagePath>/</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="../README.md">
      <Pack>True</Pack>
      <PackagePath>/</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
