name: .NET Core

on:
  push:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - uses: bbonkr/get-version-action@v1.0.4
        id: get_version
        with:
          project: "src/Serilog.Sinks.GrafanaLoki.csproj"
      - name: logging
        run: |
          echo "Version=${{steps.get_version.outputs.version}}"
