name: .NET publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # 1. Grant write permission for the OIDC id-token
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal
      - name: Package
        run: dotnet pack --no-build --configuration Release src/Serilog.Sinks.GrafanaLoki.csproj --output .
      - uses: bbonkr/get-version-action@v1
        id: get_version
        with:
          project: "src/Serilog.Sinks.GrafanaLoki.csproj"
      - name: NuGet Login
        uses: NuGet/login@v1
        id: nuget_login
        with:
          user: 'adeotek'

      # 3. Use the dynamic output token instead of ${{ secrets.NUGET_API_KEY }}
      - name: Publish to NuGet.org
        run: dotnet nuget push --source "https://api.nuget.org/v3/index.json" --api-key ${{ steps.nuget_login.outputs.token }} ./Serilog.Sinks.GrafanaLoki.${{ steps.get_version.outputs.version }}.nupkg
