name: .NET Core

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    name: Github Actions Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build Reason
      run: echo ${{github.ref}} and ${{github.event_name}}
    - name: Build
      run: dotnet build --configuration Release --nologo
    - name: Test
      run: dotnet test --configuration Release --no-build --nologo
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
